// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Copyright (c) 2026 Jiaqi Duan
/**
 * LLM-derived architecture view — the generated C4 model document schema.
 *
 * The Brain emits an `ArchModelDoc`: a semantic C4 model (bands + containers +
 * verb-labeled edges + ext systems + purposes), every claim carrying `[file:line]`
 * evidence, and NO coordinates (layout is generated by code at render time).
 *
 * `tier` ("cited" | "inferred") is filled by the grounding pass, NEVER by the
 * LLM — the model only proposes + cites; code falsifies. So `tier` is OPTIONAL in
 * the wire schema (absent on a fresh generate, populated post-grounding).
 *
 * Validation is strict + atomic: a malformed document fails as a typed error and
 * is NEVER persisted half-built. `parseArchDocFromText` tolerates
 * a ```json fence wrapper but nothing structurally looser.
 */
import { z } from "zod";

const evidenceItem = z.object({
  file: z.string().min(1),
  line: z.number().int().nonnegative(),
  endLine: z.number().int().nonnegative().optional(),
});
export const evidenceSchema = z.array(evidenceItem);
export type Evidence = z.infer<typeof evidenceSchema>;

// `topology-blind`: a band that is an omnipresent-shaped domain core
// (high-in / low-out, I≈0) AND in conflict with the net-degree gradient — import
// topology structurally cannot adjudicate its layer (it is indistinguishable from
// an infra sink). NOT `cited` (topology didn't confirm) and NOT `inferred` (there
// is no topology signal to infer from — only the LLM's own proposal). Honest
// abstention; excluded from groundedPct (neither numerator nor denominator).
export const tierSchema = z.enum(["cited", "inferred", "topology-blind"]);
export type Tier = z.infer<typeof tierSchema>;

/** A single LLM claim: a value + its supporting citations. `tier` is set by the
 * grounding pass, so it is optional on the wire. */
function claim<T extends z.ZodTypeAny>(value: T) {
  return z.object({ value, evidence: evidenceSchema, tier: tierSchema.optional() });
}

export const archBandDoc = z.object({
  id: z.string().min(1),
  label: claim(z.string().min(1)),
  /** Vertical order top→bottom as the LLM proposes it (grounding pass corroborates). */
  order: z.number().int().nonnegative(),
  /** Container ids that live in this band. */
  members: z.array(z.string()),
});
export type ArchBandDoc = z.infer<typeof archBandDoc>;

export const archNodeDoc = z.object({
  id: z.string().min(1),
  kind: z.enum(["cont", "person", "ext"]),
  title: claim(z.string().min(1)),
  /** Band id this node belongs to (layer-label judgment — corroborated by the grounding pass). */
  band: claim(z.string()),
  /** One-line purpose (judgment). */
  desc: claim(z.string()).optional(),
  /** Subdir id for cont nodes → existing drillToFile. */
  drillTo: z.string().optional(),
  /** Member file paths for grounding membership (fact tier). */
  members: z.array(z.string()).optional(),
});
export type ArchNodeDoc = z.infer<typeof archNodeDoc>;

export const archEdgeDoc = z.object({
  source: z.string().min(1),
  target: z.string().min(1),
  /** Relationship verb (judgment — corroborated by snippet-token in the grounding pass). */
  verb: claim(z.string()),
});
export type ArchEdgeDoc = z.infer<typeof archEdgeDoc>;

export const archModelDoc = z.object({
  /** System boundary label = the repo name (no provenance baked in — OQ-2). */
  boundary: z.string().min(1),
  bands: z.array(archBandDoc),
  nodes: z.array(archNodeDoc),
  edges: z.array(archEdgeDoc),
  /** Grounded share, filled by the grounding pass (cited / total). Absent on fresh generate. */
  groundedPct: z.number().min(0).max(100).optional(),
});
export type ArchModelDoc = z.infer<typeof archModelDoc>;

export type ValidateResult =
  | { ok: true; doc: ArchModelDoc }
  | { ok: false; error: string };

/** Strict validation. Returns a typed failure (never throws, never partial). */
export function validateArchDoc(raw: unknown): ValidateResult {
  const parsed = archModelDoc.safeParse(raw);
  if (parsed.success) return { ok: true, doc: parsed.data };
  const first = parsed.error.issues[0];
  const where = first?.path.join(".") || "(root)";
  return { ok: false, error: `arch-model invalid at ${where}: ${first?.message ?? "unknown"}` };
}

/**
 * Extract + validate an ArchModelDoc from raw Brain text. Tolerates a single
 * ```json fence wrapper (the model often wraps JSON), but the inner payload must
 * be structurally valid — malformed → typed error, no salvage, no partial.
 */
export function parseArchDocFromText(text: string): ValidateResult {
  const trimmed = text.trim();
  // Pull the first fenced block if present, else the first {...} span.
  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/);
  const candidate = fenced ? fenced[1]!.trim() : trimmed;
  let json: unknown;
  try {
    json = JSON.parse(candidate);
  } catch {
    // Last resort: first balanced-looking object span (handles prose preamble).
    const span = candidate.match(/\{[\s\S]*\}/);
    if (!span) return { ok: false, error: "no JSON object found in Brain output" };
    try {
      json = JSON.parse(span[0]);
    } catch (e) {
      return { ok: false, error: `JSON parse failed: ${e instanceof Error ? e.message : "unknown"}` };
    }
  }
  return validateArchDoc(json);
}
