// SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.1
// Copyright (c) 2026 Jiaqi Duan
/**
 * Canonical design tokens.
 *
 * Single source of truth for colors / fonts / spacing / radius / shadows
 * referenced by both:
 *   - JSX SSR (`style={{ background: tokens.color.cream }}`)
 *   - The generated `tokens.css` file (CSS custom properties on `:root`),
 *     produced by `scripts/build-tokens.ts`.
 *
 * Adding a new token:
 *   1. Add to the const map below.
 *   2. Run `bun scripts/build-tokens.ts` (auto-runs on daemon start).
 *   3. The CSS var is automatically exposed as `--<category>-<key>`.
 */
import {
  palette,
  shadowPalette,
  keywordColors,
  graphPalette,
  kindPalette,
  type ColorToken,
  type ShadowToken,
  type ThemeName,
  type GraphToken,
  type KindToken,
} from "./palette";

export type { ColorToken, ThemeName, ShadowToken, GraphToken, KindToken } from "./palette";
export { palette, contrastRatio, relativeLuminance, graphPalette, kindPalette } from "./palette";

const colorVars = Object.fromEntries(
  (Object.keys(palette.light) as ColorToken[]).map((k) => [k, `var(--color-${k})`]),
) as Record<ColorToken, string>;

const shadowVars = Object.fromEntries(
  (Object.keys(shadowPalette.light) as ShadowToken[]).map((k) => [k, `var(--shadow-${k})`]),
) as Record<ShadowToken, string>;

const graphVars = Object.fromEntries(
  (Object.keys(graphPalette.light) as GraphToken[]).map((k) => [k, `var(--graph-${k})`]),
) as Record<GraphToken, string>;

const kindVars = Object.fromEntries(
  (Object.keys(kindPalette.light) as KindToken[]).map((k) => [k, `var(--kind-${k})`]),
) as Record<KindToken, string>;

export const tokens = {
  color: colorVars,
  graph: graphVars,
  kind: kindVars,
  font: {
    display: '"Pixelify Sans", system-ui, sans-serif',
    mono: '"JetBrains Mono", ui-monospace, monospace',
    body: '"Geist", system-ui, sans-serif',
  },
  space: {
    "1": "4px",
    "1_5": "6px",
    "2": "8px",
    "3": "12px",
    "3_5": "14px",
    "4": "16px",
    "4_5": "18px",
    "5": "22px",
    "6": "24px",
  },
  radius: {
    sm: "4px",
    md: "8px",
    lg: "14px",
    pill: "999px",
  },
  shadow: shadowVars,
} as const;

export type Tokens = typeof tokens;
export type FontToken = keyof typeof tokens.font;
export type SpaceToken = keyof typeof tokens.space;
export type RadiusToken = keyof typeof tokens.radius;

function themeVars(theme: ThemeName, indent: string): string {
  const lines: string[] = [`${indent}color-scheme: ${theme};`];
  for (const [key, value] of Object.entries(palette[theme])) {
    lines.push(`${indent}--color-${key}: ${value};`);
  }
  for (const [key, value] of Object.entries(shadowPalette[theme])) {
    lines.push(`${indent}--shadow-${key}: ${value};`);
  }
  for (const [key, value] of Object.entries(graphPalette[theme])) {
    lines.push(`${indent}--graph-${key}: ${value};`);
  }
  for (const [key, value] of Object.entries(kindPalette[theme])) {
    lines.push(`${indent}--kind-${key}: ${value};`);
  }
  return lines.join("\n");
}

function staticVars(indent: string): string {
  const lines: string[] = [];
  for (const cat of ["font", "space", "radius"] as const) {
    for (const [key, value] of Object.entries(tokens[cat])) {
      lines.push(`${indent}--${cat}-${key}: ${value};`);
    }
  }
  return lines.join("\n");
}

/**
 * Render the four theme CSS blocks — `:root` (light default + static tokens),
 * the `prefers-color-scheme: dark` media block, the forced `[data-theme=dark]`
 * block, and the forced `[data-theme=light]` block. Used by
 * `scripts/build-tokens.ts` to emit `tokens.css`.
 *
 * Four blocks, IN THIS ORDER. The order is load-bearing: the forced-light block
 * must follow the media block or "user forces light on a dark OS" resolves dark.
 * tests/web/tokens/generated-css.test.ts pins it.
 */
export function tokensToCss(): string {
  return [
    "/* GENERATED by scripts/build-tokens.ts — do not hand-edit. */",
    ":root {",
    themeVars("light", "  "),
    staticVars("  "),
    "}",
    "",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    themeVars("dark", "    "),
    "  }",
    "}",
    "",
    ':root[data-theme="dark"] {',
    themeVars("dark", "  "),
    "}",
    "",
    ':root[data-theme="light"] {',
    themeVars("light", "  "),
    "}",
    "",
  ].join("\n");
}

/**
 * The Tailwind v4 `@theme` body. Holds LITERAL light hex — a var() here would
 * point at the variable Tailwind is defining. Dark values do not belong here;
 * they come from tokens.css, which wins by being unlayered (Task 1 pins this).
 */
export function tokensToTailwindTheme(): string {
  const lines = [
    "  /* GENERATED by scripts/build-tokens.ts — do not hand-edit. */",
    "  /* Drop Tailwind's default palette — keep only our brand colors + the",
    "     keyword colors utilities rely on (bg-transparent, text-white, …). */",
    "  --color-*: initial;",
  ];
  for (const [key, value] of Object.entries(keywordColors)) {
    lines.push(`  --color-${key}: ${value};`);
  }
  lines.push("");
  for (const [key, value] of Object.entries(palette.light)) {
    lines.push(`  --color-${key}: ${value};`);
  }
  lines.push("");
  for (const cat of ["font", "radius"] as const) {
    for (const [key, value] of Object.entries(tokens[cat])) {
      lines.push(`  --${cat}-${key}: ${value};`);
    }
  }
  return lines.join("\n");
}

/**
 * Read a token's ACTIVE color as a real value. Browser-only by construction.
 *
 * Prefer NOT to use this. The CSS-native replacement for "this color at N%
 * alpha" is `color-mix(in srgb, var(--color-x) N%, transparent)`, which themes
 * live with no JS at all. readColor exists for the cases where a real string is
 * unavoidable.
 *
 * Three constraints, each from the design review:
 *   - SSR guard: `document` is undefined during Hono SSR.
 *   - Fail loud on empty: getPropertyValue returns "" for an undefined property
 *     or before the stylesheet is parsed. Returning "" silently produces NaN
 *     colors downstream.
 *   - Never call inside a render loop: getComputedStyle forces a synchronous
 *     style recalculation. Cache per theme change, not per frame.
 */
export function readColor(key: ColorToken): string {
  if (typeof document === "undefined") return palette.light[key];
  const value = getComputedStyle(document.documentElement)
    .getPropertyValue(`--color-${key}`)
    .trim();
  if (!value) {
    throw new Error(`readColor: --color-${key} did not resolve (stylesheet not loaded?)`);
  }
  return value;
}
