#!/usr/bin/env bun
// SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.1
// Copyright (c) 2026 Jiaqi Duan
import { mkdir, writeFile, readdir, rm, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { Database } from "bun:sqlite";
import { Tracer } from "../observability/tracer";
import { TraceStore } from "../observability/storage";
import { buildRepoMemoryIndex } from "../repo-memory/index-builder";
import { buildFewShotIndex } from "../few-shot/build-index";

const argv = process.argv.slice(2);
const flagClear = argv.includes("--clear");
const flagSkipBuild = argv.includes("--skip-build");

// Resolve HOME lazily so SILTPOKE_HOME env can be set before calling main()
function getHome(): string {
  return process.env.SILTPOKE_HOME ?? join(homedir(), ".siltpoke");
}

const today = new Date().toISOString().slice(0, 10);

// ── Critiques ──────────────────────────────────────────────────────────────

interface EvidenceEntry {
  rule_id: string;
  tier: number;
  file: string;
  line: number;
  snippet: string;
  signal_source: string;
}

interface CritiqueSpec {
  id: string;
  severity: string;
  confidence: string;
  category: string;
  intent: string;
  intent_conf: number;
  reasoning: string;
  critique_for_claude: string;
  suggested_fix: string;
  bubble_short: string;
  evidence: EvidenceEntry[];
  /** Captured user query for Block A demo. */
  user_raw_query?: string;
}

const CRITIQUES: CritiqueSpec[] = [
  {
    id: "c-demo-bug-001",
    severity: "high",
    confidence: "high",
    category: "security",
    intent: "bugfix",
    intent_conf: 0.92,
    reasoning:
      "AWS key embedded in source. Even test/example values leak into git history. Detected via the secrets scanner.",
    critique_for_claude:
      "Move 'AKIA...' to process.env. Don't commit secrets even in tests.",
    suggested_fix: "const accessKey = process.env.AWS_ACCESS_KEY;",
    bubble_short: "ouch secret in source",
    user_raw_query: "add AWS integration for the legacy auth module",
    evidence: [
      {
        rule_id: "aws-access-key",
        tier: 1,
        file: "src/auth/legacy.ts",
        line: 18,
        snippet: "const accessKey = 'AKIAIOSFODNN7EXAMPLE'",
        signal_source: "secrets-scan",
      },
    ],
  },
  {
    id: "c-demo-design-002",
    severity: "med",
    confidence: "med",
    category: "design",
    intent: "feature",
    intent_conf: 0.81,
    reasoning:
      "New file added 6 positional parameters. House convention favors object args. AST rule long-param-list flagged.",
    critique_for_claude:
      "Refactor checkAccess to accept { user, resource, action, context, ... } object arg instead of 6 positional.",
    suggested_fix:
      "function checkAccess(opts: { user: User; resource: string; action: string; ... }) { ... }",
    bubble_short: "lots of args",
    user_raw_query: "add role-based access control with per-resource scoping",
    evidence: [
      {
        rule_id: "long-param-list",
        tier: 2,
        file: "src/access/check.ts",
        line: 12,
        snippet:
          "function checkAccess(user, resource, action, context, scope, traceId)",
        signal_source: "rubric-tier2",
      },
      {
        rule_id: "boolean-param",
        tier: 2,
        file: "src/access/check.ts",
        line: 24,
        snippet: "checkAccess(u, 'doc', 'read', null, true, t)",
        signal_source: "rubric-tier2",
      },
    ],
  },
];

async function writeCritique(c: CritiqueSpec): Promise<void> {
  const dir = join(getHome(), "critiques", "archive", today);
  await mkdir(dir, { recursive: true });
  const evidenceYaml = c.evidence
    .map(
      (e) =>
        `  - rule_id: ${e.rule_id}\n    tier: ${e.tier}\n    file: ${e.file}\n    line: ${e.line}\n    snippet: "${e.snippet.replace(/"/g, '\\"')}"\n    signal_source: ${e.signal_source}`,
    )
    .join("\n");

  // Captured user query for Block A demo.
  const capturedIntentLines = c.user_raw_query
    ? `user_raw_query: ${JSON.stringify(c.user_raw_query)}`
    : "user_raw_query: null";

  const md = `---
schemaVersion: 2
critique_id: ${c.id}
ts: ${new Date().toISOString()}
intent_classification: ${c.intent}
intent_confidence: ${c.intent_conf}
category: ${c.category}
severity: ${c.severity}
confidence: ${c.confidence}
status: pending
signal_sources: [${c.evidence.map((e) => e.signal_source).join(", ")}]
reasoning: ${JSON.stringify(c.reasoning)}
critique_for_claude: ${JSON.stringify(c.critique_for_claude)}
suggested_fix: ${JSON.stringify(c.suggested_fix)}
mood: concerned
pose: base
bubble_short: ${JSON.stringify(c.bubble_short)}
bubble_long: ""
xp_earned_events: []
evidence:
${evidenceYaml}
${capturedIntentLines}
---
Demo seed critique — ${c.id}. Generated by \`bun src/cli/demo-seed.ts\`.
`;
  await writeFile(join(dir, `${c.id}.md`), md);
}

// ── Traces ─────────────────────────────────────────────────────────────────

async function writeTraceFor(critiqueId: string): Promise<void> {
  const tracesDir = join(getHome(), "traces");
  await mkdir(tracesDir, { recursive: true });
  const tracer = new Tracer();
  const store = new TraceStore({ dir: tracesDir, dbPath: join(tracesDir, "index.sqlite") });

  // Root span — siltpoke.turn (chain kind)
  const root = tracer.startSpan({
    name: "siltpoke.turn",
    kind: "INTERNAL",
    attributes: { "siltpoke.critique_id": critiqueId },
  });
  tracer.setKind(root, "chain");
  tracer.setAttribute(root, "siltpoke.demo", true);
  tracer.setInput(root, {
    "[DEMO]": "This trace is synthetic data from `bun src/cli/demo-seed.ts` — not produced by a real critic fire. Inputs/outputs below illustrate the trace UI shape; they don't reflect actual scans of your repo.",
    source: "stop-hook",
    critique_id: critiqueId,
    changed_files: 5,
  });
  await new Promise((r) => setTimeout(r, 3));

  // Rubric span
  const rubric = tracer.startSpan({
    name: "siltpoke.rubric.tier1",
    kind: "INTERNAL",
    parent: root,
  });
  tracer.setKind(rubric, "rubric");
  tracer.setInput(rubric, { changed_files: 5, rules_count: 13 });
  await new Promise((r) => setTimeout(r, 8));
  tracer.setAttribute(rubric, "siltpoke.rules.count", 13);
  tracer.setAttribute(rubric, "siltpoke.triggers.count", 2);
  tracer.setOutput(rubric, { triggers: 2, errors: 0 });
  tracer.endSpan(rubric, { status: "OK" });

  // Summarizer span (Haiku diff-summary — LLM kind)
  const summarizerSpan = tracer.startSpan({
    name: "siltpoke.summarizer.haiku",
    kind: "CLIENT",
    parent: root,
    attributes: {
      "gen_ai.system": "anthropic",
      "gen_ai.request.model": "claude-haiku-4-5",
      "siltpoke.kind": "llm",
      "gen_ai.usage.input_tokens": 620,
      "gen_ai.usage.output_tokens": 180,
    },
  });
  tracer.setKind(summarizerSpan, "llm");
  tracer.setInput(summarizerSpan, {
    diff_bytes: 4200,
    system_prompt_truncated: "You are a code-diff summarizer. Read the unified diff",
  });
  await new Promise((r) => setTimeout(r, 5));
  tracer.setOutput(summarizerSpan, {
    intent: "Add AWS integration for legacy auth module",
    file_count: 3,
    risks_count: 1,
    source: "haiku",
  });
  tracer.endSpan(summarizerSpan, { status: "OK" });

  // Brain find span (LLM kind)
  const brain = tracer.startSpan({
    name: "siltpoke.brain.find",
    kind: "CLIENT",
    parent: root,
    attributes: {
      "gen_ai.system": "anthropic",
      "gen_ai.request.model": "claude-haiku-4-5-20251001",
      "gen_ai.usage.input_tokens": 1450,
      "gen_ai.usage.output_tokens": 320,
    },
  });
  tracer.setKind(brain, "llm");
  tracer.setInput(brain, {
    messages: [
      {
        role: "system",
        content:
          "You are Siltpoke critic. Review the diff per the 13-rule rubric and emit one JSON object.",
      },
      {
        role: "user",
        content:
          "User added a null guard in auth middleware. Please review and return Siltpoke JSON.",
      },
    ],
  });
  await new Promise((r) => setTimeout(r, 14));
  tracer.setOutput(brain, {
    mood: "concerned",
    severity: "high",
    critique_for_claude: "Move AKIA secret to env",
  });
  tracer.endSpan(brain, { status: "OK" });

  // Demo file list — referenced by all tool span inputs so user can see what was scanned.
  const DEMO_FILES = [
    "src/auth/middleware.ts",
    "src/auth/login.ts",
    "src/access/check.ts",
    "src/api/handler.ts",
    "tests/auth.test.ts",
  ];

  // Tool span — tsc check (child of root, demonstrates Tools tab)
  const toolSpan = tracer.startSpan({
    name: "siltpoke.tool.tsc",
    kind: "INTERNAL",
    parent: root,
  });
  tracer.setKind(toolSpan, "tool");
  tracer.setInput(toolSpan, {
    "[DEMO]": "synthetic data from demo-seed CLI — not from a real critique run",
    argv: ["bunx", "tsc", "--noEmit"],
    files_checked: DEMO_FILES,
    cwd: "/path/to/project",
  });
  tracer.setAttribute(toolSpan, "siltpoke.tool.name", "tsc");
  tracer.setAttribute(toolSpan, "siltpoke.tool.status", "ok");
  await new Promise((r) => setTimeout(r, 5));
  tracer.setOutput(toolSpan, {
    "[DEMO]": "synthetic",
    status: "ok",
    errors: 0,
    files_checked: DEMO_FILES.length,
    duration_ms: 4200,
  });
  tracer.endSpan(toolSpan, { status: "OK" });

  // Tool span — eslint check (second tool span)
  const eslintSpan = tracer.startSpan({
    name: "siltpoke.tool.eslint",
    kind: "INTERNAL",
    parent: root,
  });
  tracer.setKind(eslintSpan, "tool");
  tracer.setInput(eslintSpan, {
    "[DEMO]": "synthetic",
    argv: ["bunx", "eslint", "--format=json", ...DEMO_FILES],
    files_checked: DEMO_FILES,
    cwd: "/path/to/project",
  });
  tracer.setAttribute(eslintSpan, "siltpoke.tool.name", "eslint");
  tracer.setAttribute(eslintSpan, "siltpoke.tool.status", "ok");
  await new Promise((r) => setTimeout(r, 3));
  tracer.setOutput(eslintSpan, {
    "[DEMO]": "synthetic",
    status: "ok",
    errors: 0,
    warnings: 1,
    files_checked: DEMO_FILES.length,
    duration_ms: 1800,
  });
  tracer.endSpan(eslintSpan, { status: "OK" });

  // Tool span — secrets-scan (third tool span)
  // For the AWS-key critique (c-demo-bug-001) we emit a synthetic AKIA finding so
  // the Tools tab shows what a real hit looks like. For other demo critiques
  // (e.g. c-demo-design-002) we keep findings empty to avoid implying AWS usage.
  const isSecretsDemo = critiqueId === "c-demo-bug-001";
  const secretsSpan = tracer.startSpan({
    name: "siltpoke.tool.secrets-scan",
    kind: "INTERNAL",
    parent: root,
  });
  tracer.setKind(secretsSpan, "tool");
  tracer.setInput(secretsSpan, {
    "[DEMO]": "synthetic",
    files_checked: DEMO_FILES,
    patterns_loaded: ["aws-access-key", "github-pat", "stripe-secret", "anthropic-api"],
  });
  tracer.setAttribute(secretsSpan, "siltpoke.tool.name", "secrets-scan");
  tracer.setAttribute(secretsSpan, "siltpoke.tool.status", "ok");
  await new Promise((r) => setTimeout(r, 2));
  tracer.setOutput(secretsSpan, isSecretsDemo
    ? {
        "[DEMO]": "synthetic — matches the AWS-key demo critique c-demo-bug-001",
        status: "ok",
        findings: [
          {
            file: "src/auth/legacy.ts",
            line: 18,
            pattern: "aws-access-key",
            snippet: "const accessKey = 'AKIAIOSFODNN7EXAMPLE'",
          },
        ],
        files_checked: DEMO_FILES.length,
      }
    : {
        "[DEMO]": "synthetic — no real secrets in your repo",
        status: "ok",
        findings: [],
        files_checked: DEMO_FILES.length,
      });
  tracer.endSpan(secretsSpan, { status: "OK" });

  // Brain verify span (LLM kind)
  const verify = tracer.startSpan({
    name: "siltpoke.brain.verify",
    kind: "CLIENT",
    parent: root,
    attributes: {
      "gen_ai.system": "anthropic",
      "gen_ai.usage.input_tokens": 800,
      "gen_ai.usage.output_tokens": 120,
    },
  });
  tracer.setKind(verify, "llm");
  tracer.setInput(verify, {
    messages: [
      {
        role: "user",
        content:
          "Verify the previous critique. Are all findings grounded in the diff?",
      },
    ],
  });
  await new Promise((r) => setTimeout(r, 6));
  tracer.setOutput(verify, { ungrounded_ids: [] });
  tracer.endSpan(verify, { status: "OK" });

  tracer.setOutput(root, { decision: "PASSIVE_BUBBLE", severity: "info" });
  tracer.endSpan(root, { status: "OK" });

  for (const s of [root, rubric, summarizerSpan, brain, toolSpan, eslintSpan, secretsSpan, verify]) {
    await store.writeSpan(s);
  }
}

// ── Bias audit sample ──────────────────────────────────────────────────────

async function writeBiasAuditSamples(): Promise<void> {
  const dir = join(getHome(), "bias-audit");
  await mkdir(dir, { recursive: true });
  const file = join(dir, `${today}.jsonl`);
  const lines = [
    JSON.stringify({
      ts: new Date().toISOString(),
      haiku: { severity: "high", confidence: "high", category: "security" },
      ollama: { severity: "high", confidence: "high", category: "security" },
    }),
    JSON.stringify({
      ts: new Date().toISOString(),
      haiku: { severity: "med", confidence: "med", category: "design" },
      ollama: { severity: "low", confidence: "med", category: "design" },
    }),
    JSON.stringify({
      ts: new Date().toISOString(),
      haiku: { severity: "med", confidence: "high", category: "tests" },
      ollama: { severity: "med", confidence: "high", category: "tests" },
    }),
  ];
  await writeFile(file, `${lines.join("\n")}\n`);
}

// ── Optionally clear demo data ─────────────────────────────────────────────

/** Prefix patterns that identify demo/smoke seeded spans */
const DEMO_PREFIXES = ["c-demo-", "c-smoke-"];

function isDemoId(id: string | null | undefined): boolean {
  if (!id) return false;
  return DEMO_PREFIXES.some((p) => id.startsWith(p));
}

export async function clearDemoData(): Promise<void> {
  // 1. Remove c-demo-* critique markdown files
  const dayDir = join(getHome(), "critiques", "archive", today);
  if (existsSync(dayDir)) {
    const files = await readdir(dayDir);
    for (const f of files) {
      if (f.startsWith("c-demo-")) {
        await rm(join(dayDir, f));
      }
    }
  }

  // 2. Wipe demo spans from SQLite index
  const tracesDir = join(getHome(), "traces");
  const dbPath = join(tracesDir, "index.sqlite");
  if (existsSync(dbPath)) {
    const db = new Database(dbPath);
    const _result = db.exec(
      `DELETE FROM spans WHERE critique_id LIKE 'c-demo-%' OR critique_id LIKE 'c-smoke-%'`
    );
    db.close();
  }

  // 3. Filter demo span lines from JSONL files
  if (existsSync(tracesDir)) {
    const jsonlFiles = (await readdir(tracesDir)).filter((f) => f.endsWith(".jsonl"));
    for (const f of jsonlFiles) {
      const filePath = join(tracesDir, f);
      const raw = await readFile(filePath, "utf8");
      const lines = raw.split("\n").filter((l) => l.trim() !== "");
      const kept = lines.filter((l) => {
        try {
          const span = JSON.parse(l) as { attributes?: Record<string, unknown> };
          const cid = span.attributes?.["siltpoke.critique_id"] as string | undefined;
          return !isDemoId(cid);
        } catch {
          return true; // keep malformed lines rather than lose data
        }
      });
      if (kept.length !== lines.length) {
        const _removed = lines.length - kept.length;
        await writeFile(filePath, kept.length > 0 ? `${kept.join("\n")}\n` : "");
      }
    }
  }
}

// ── Main ───────────────────────────────────────────────────────────────────

export async function main(): Promise<void> {

  if (flagClear) {
    await clearDemoData();
  }
  for (const c of CRITIQUES) await writeCritique(c);
  for (const c of CRITIQUES) await writeTraceFor(c.id);
  await writeBiasAuditSamples();

  if (!flagSkipBuild) {
    const cwd = process.cwd();
    const _idx = await buildRepoMemoryIndex({
      cwd,
      pattern: "src/critic/**/*.ts",
    });
    const _fs = await buildFewShotIndex({});
  } else {
  }
}

// Run when invoked directly (not imported in tests)
if (import.meta.main) {
  main().catch((e: unknown) => {
    console.error("\nSeed failed:", e);
    process.exit(1);
  });
}
