// SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.1
// Copyright (c) 2026 Jiaqi Duan
/**
 * v1.1-J — `/siltpoke-undismiss <critique_id>` CLI.
 *
 * Reverses a previously dismissed critique:
 *   1. Flip status `dismissed` → `pending` in the critique frontmatter.
 *   2. Look up the dismissal entry in feedback-archive.jsonl to find
 *      the rule_id (if any) generated by reflection.
 *   3. Remove that learned_rule from memory.json — but ONLY when it's
 *      safe: when the original dismissal created the rule (not when
 *      reflection merely matched an existing duplicate that other
 *      critiques may still rely on).
 *   4. Append an audit entry to feedback-archive with verdict
 *      "undismissed" so the timeline is reconstructable.
 */
import { join } from "node:path";
import {
  findCritiqueByIdOrLatest,
  setStatus,
  readStatus,
} from "../state/critique-status";
import {
  appendFeedbackArchive,
  findDismissalEntry,
  readFeedbackArchive,
  type FeedbackArchiveEntry,
} from "../memory/feedback-archive";
import { removeLearnedRuleById } from "../memory/memory";
import { siltpokeRoot } from "../installer/paths";

function projectSiltpoke(cwd: string): string {
  return join(cwd, ".siltpoke");
}

export interface UndismissOptions {
  critiqueId: string;
  cwd: string;
  /** Per-project base for critique lookup. Defaults to {cwd}/.siltpoke/. */
  projectBase?: string;
  /** Global base for feedback-archive read/write. Defaults to ~/.siltpoke/. */
  homeBase?: string;
  now?: () => Date;
}

export type RuleKeptReason = "shared" | "legacy_shared" | null;

export interface UndismissResult {
  undismissed: boolean;
  critique_id: string;
  /** "pending" on success, "not_found" when the critique id doesn't resolve, "wasnt_dismissed" when already pending. */
  status_set: "pending" | "not_found" | "wasnt_dismissed";
  /** What the critique's status was before this call. null when not_found. */
  was_status: string | null;
  rule_removed: boolean;
  rule_id: string | null;
  /** Why the rule was kept when we knew about it but chose not to remove. */
  rule_kept_reason: RuleKeptReason;
}

/**
 * Decide whether the dismissal's learned_rule is safe to remove on undismiss.
 *
 * - `rule_created === true` → THIS dismissal appended a NEW rule → safe to remove.
 * - `rule_created === false` → reflection matched a DUPLICATE rule that
 *   belongs to another critique → never remove.
 * - `rule_created === undefined` → legacy entry (pre-v1.1-J). Fall back
 *   to a chronological scan: if this is the FIRST archive entry with
 *   that rule_id → safe (we likely created it). If earlier entries
 *   reference the same rule_id → legacy shared rule → keep.
 */
async function decideRuleRemoval(
  homeBase: string,
  dismissalEntry: FeedbackArchiveEntry,
): Promise<{ should_remove: boolean; rule_kept_reason: RuleKeptReason }> {
  const ruleCreated = dismissalEntry.reflection?.rule_created;
  if (ruleCreated === true) return { should_remove: true, rule_kept_reason: null };
  if (ruleCreated === false) return { should_remove: false, rule_kept_reason: "shared" };

  // Legacy entry — chronological scan fallback.
  const rule_id = dismissalEntry.reflection?.rule_id;
  if (!rule_id) return { should_remove: false, rule_kept_reason: null }; // no rule to consider
  const all = await readFeedbackArchive(homeBase);
  // Scan oldest → newest. The FIRST entry whose reflection.rule_id matches
  // is the one that created the rule (under append-only assumptions).
  for (const e of all) {
    if (e.reflection?.rule_id === rule_id) {
      // If THIS dismissal entry is the earliest match, safe to remove.
      if (e.ts === dismissalEntry.ts && e.critique_id === dismissalEntry.critique_id) {
        return { should_remove: true, rule_kept_reason: null };
      }
      // Earlier entry exists with same rule_id → rule was created elsewhere.
      return { should_remove: false, rule_kept_reason: "legacy_shared" };
    }
  }
  // Shouldn't get here (dismissalEntry itself is in the archive), but guard.
  return { should_remove: false, rule_kept_reason: null };
}

export async function runUndismiss(opts: UndismissOptions): Promise<UndismissResult> {
  const homeBase = opts.homeBase ?? siltpokeRoot();
  const projectBase = opts.projectBase ?? projectSiltpoke(opts.cwd);
  const now = opts.now ?? (() => new Date());

  const critiquePath = await findCritiqueByIdOrLatest(projectBase, opts.critiqueId);
  if (!critiquePath) {
    return {
      undismissed: false,
      critique_id: opts.critiqueId,
      status_set: "not_found",
      was_status: null,
      rule_removed: false,
      rule_id: null,
      rule_kept_reason: null,
    };
  }

  const previous = await readStatus(critiquePath);
  if (previous !== "dismissed") {
    return {
      undismissed: false,
      critique_id: opts.critiqueId,
      status_set: "wasnt_dismissed",
      was_status: previous,
      rule_removed: false,
      rule_id: null,
      rule_kept_reason: null,
    };
  }

  await setStatus(critiquePath, "pending");

  // Find the dismissal that created the (possibly-null) rule.
  const dismissalEntry = await findDismissalEntry(homeBase, opts.critiqueId);
  const rule_id = dismissalEntry?.reflection?.rule_id ?? null;

  let rule_removed = false;
  let rule_kept_reason: RuleKeptReason = null;

  if (rule_id !== null && dismissalEntry !== null) {
    const decision = await decideRuleRemoval(homeBase, dismissalEntry);
    rule_kept_reason = decision.rule_kept_reason;
    if (decision.should_remove) {
      // Rules live in the canonical V3 store (homeBase) — dismiss (Task 4)
      // appends there, so the rollback must remove from the same base.
      // projectBase is still used for critique lookup above; it must NOT be
      // touched here.
      const r = await removeLearnedRuleById(homeBase, rule_id);
      rule_removed = r.removed;
    }
  }

  // Audit trail: append an "undismissed" entry to the feedback archive.
  await appendFeedbackArchive(homeBase, {
    ts: now().toISOString(),
    critique_id: opts.critiqueId,
    verdict: "undismissed",
    reason: null,
    reverses_critique_id: opts.critiqueId,
    reflection: {
      rule_id,
      rule_category: dismissalEntry?.reflection?.rule_category ?? null,
      confidence: dismissalEntry?.reflection?.confidence ?? null,
    },
  });

  return {
    undismissed: true,
    critique_id: opts.critiqueId,
    status_set: "pending",
    was_status: "dismissed",
    rule_removed,
    rule_id,
    rule_kept_reason,
  };
}

export function formatUndismissHuman(result: UndismissResult): string {
  if (result.status_set === "not_found") {
    return `siltpoke-undismiss: review ${result.critique_id} not found.\n`;
  }
  if (result.status_set === "wasnt_dismissed") {
    return `Review ${result.critique_id} wasn't dismissed (status: ${result.was_status}). No change.\n`;
  }
  const head = `Review ${result.critique_id} restored. Status: dismissed → pending.`;
  if (result.rule_id === null) {
    return `${head}\nNo learned rule was created by this dismissal (low reflection confidence). Nothing else to undo.\n`;
  }
  if (result.rule_removed) {
    return `${head}\nLearned rule ${result.rule_id} removed (was generated by this dismissal).\n`;
  }
  // rule existed but kept
  const reason =
    result.rule_kept_reason === "shared"
      ? "also referenced by other dismissals"
      : result.rule_kept_reason === "legacy_shared"
        ? "predates v1.1-J tracking; likely created by an earlier dismissal"
        : "kept";
  return `${head}\nLearned rule ${result.rule_id} kept — ${reason}. Edit memory.json manually if you want to remove it.\n`;
}

export function formatUndismissJson(result: UndismissResult): string {
  return `${JSON.stringify(result, null, 2)}\n`;
}

if (import.meta.main) {
  const argv = process.argv.slice(2);
  const jsonFlag = argv.includes("--json");
  const positional = argv.filter((a) => !a.startsWith("--"));
  const critiqueId = positional[0];
  if (!critiqueId) {
    process.stderr.write("siltpoke-undismiss: critique id is required. Usage: siltpoke-undismiss <critique_id> [--json]\n");
    process.exit(1);
  }
  const result = await runUndismiss({ critiqueId, cwd: process.cwd() });
  if (jsonFlag) {
    process.stdout.write(formatUndismissJson(result));
  } else if (result.status_set === "not_found") {
    process.stderr.write(formatUndismissHuman(result));
    process.exit(1);
  } else {
    process.stdout.write(formatUndismissHuman(result));
  }
  process.exit(0);
}
